type Customer = {
  id: number;
  name: string;
  phoneNumber: number;
  street: string;
  city: string;
  zip: number;
  state: string;
  email: string;
};

export const customers: Customer[] = [
  {
    id: 1,
    name: "John Doe",
    phoneNumber: 1234567890,
    street: "123 Main St",
    city: "Anytown",
    zip: 12345,
    state: "CA",
    email: "john@example.com",
  },
  {
    id: 2,
    name: "Alice Johnson",
    phoneNumber: 9876543210,
    street: "456 Elm St",
    city: "Another Town",
    zip: 54321,
    state: "NY",
    email: "alice@example.com",
  },
  {
    id: 3,
    name: "Bob Smith",
    phoneNumber: 5551234567,
    street: "789 Oak St",
    city: "Smallville",
    zip: 67890,
    state: "WA",
    email: "bob@example.com",
  },
  {
    id: 4,
    name: "Jane Anderson",
    phoneNumber: 8887776666,
    street: "101 Pine St",
    city: "Villageville",
    zip: 98765,
    state: "TX",
    email: "jane@example.com",
  },
  {
    id: 5,
    name: "Mike Wilson",
    phoneNumber: 1112223333,
    street: "111 Cedar St",
    city: "Citytown",
    zip: 11111,
    state: "CA",
    email: "mike@example.com",
  },
  {
    id: 6,
    name: "Sara Brown",
    phoneNumber: 2223334444,
    street: "222 Spruce St",
    city: "Hometown",
    zip: 22222,
    state: "NY",
    email: "sara@example.com",
  },
  {
    id: 7,
    name: "David White",
    phoneNumber: 3334445555,
    street: "333 Birch St",
    city: "Metropolis",
    zip: 33333,
    state: "IL",
    email: "david@example.com",
  },
  {
    id: 8,
    name: "Emily Davis",
    phoneNumber: 4445556666,
    street: "444 Redwood St",
    city: "Townsville",
    zip: 44444,
    state: "WA",
    email: "emily@example.com",
  },
  {
    id: 9,
    name: "Daniel Lee",
    phoneNumber: 5556667777,
    street: "555 Willow St",
    city: "Suburbia",
    zip: 55555,
    state: "CA",
    email: "daniel@example.com",
  },
  {
    id: 10,
    name: "Olivia Evans",
    phoneNumber: 6667778888,
    street: "666 Oakwood St",
    city: "Countryside",
    zip: 66666,
    state: "NY",
    email: "olivia@example.com",
  },
  {
    id: 11,
    name: "Christopher Hall",
    phoneNumber: 7778889999,
    street: "777 Cedarwood St",
    city: "Villageton",
    zip: 77777,
    state: "TX",
    email: "chris@example.com",
  },
  {
    id: 12,
    name: "Ava Lewis",
    phoneNumber: 8889990000,
    street: "888 Elmwood St",
    city: "Smallville",
    zip: 88888,
    state: "WA",
    email: "ava@example.com",
  },
];
