import Sidebar from "@/components/home/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Header from "@/components/home/Header";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="grid min-h-screen grid-rows-[100px,1fr,1fr,1fr,1fr] gap-x-0 gap-y-0 md:grid-cols-[300px,1fr,1fr,1fr,1fr]">
          <Header />
          <Sidebar />
          <div className="col-span-5 row-span-4 md:col-span-4 md:row-span-5">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
